In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
import sqlite3

# Membaca file Excel dengan nama kolom hanya dari tabel 1
file1 = pd.read_excel('01. table_transaksi_jan_2020.xlsx')
file2 = pd.read_excel('02. table_transaksi_feb_2020.xlsx', header=None)  # Mengabaikan nama kolom
file3 = pd.read_excel('03. table_transaksi_mar_2020.xlsx', header=None)  # Mengabaikan nama kolom

# Hanya menggunakan data dari file 1 untuk nama kolom
file2.columns = file1.columns  # Mengganti nama kolom tabel 2 dengan nama kolom tabel 1
file3.columns = file1.columns  # Mengganti nama kolom tabel 3 dengan nama kolom tabel 1

# Koneksi ke SQLite database (misalnya 'transaksi.db')
conn = sqlite3.connect('transaksi.db')  # Ganti dengan nama file .db yang diinginkan

# Menyimpan data dari Excel ke tabel SQL
file1.to_sql('table1', conn, if_exists='replace', index=False)
file2.to_sql('table2', conn, if_exists='replace', index=False)
file3.to_sql('table3', conn, if_exists='replace', index=False)

# SQL query untuk menggabungkan ketiga tabel
query = """
    SELECT * FROM table1
    UNION ALL
    SELECT * FROM table2
    UNION ALL
    SELECT * FROM table3
"""

# Menjalankan query dan memuat hasilnya ke dalam DataFrame
result = pd.read_sql_query(query, conn)

# Menyimpan hasil penggabungan ke tabel baru di SQLite
result.to_sql('transaksi_q1', conn, if_exists='replace', index=False)

print("Penggabungan selesai, hasil disimpan di tabel 'transaksi_q1' dalam SQLite database.")

# Menutup koneksi
conn.close()

Penggabungan selesai, hasil disimpan di tabel 'transaksi_q1' dalam SQLite database.

In [ ]:
# Koneksi ke SQLite database
conn = sqlite3.connect('transaksi.db')  # Ganti dengan nama file .db yang diinginkan

# Mengambil isi tabel 'merged_table'
query = "SELECT * FROM transaksi_q1"
q1_transactions = pd.read_sql_query(query, conn)

print(q1_transactions)

# Menutup koneksi
conn.close()

              trx_id             trx_time        rs_user    rs_id sd_id  \
0        11580811934  2020-01-01 00:00:12  6281241291242  SC46886   SRC
1        11580811942  2020-01-01 00:00:24  6282274535840  SC22072   SRC
2        11580811952  2020-01-01 00:00:39  6282386610815  SC27711   SRC
3        11580811951  2020-01-01 00:00:40  6282278506522  SC13764   SRC
4        11580811962  2020-01-01 00:00:46  6281238003443  SC35233   SRC
...              ...                  ...            ...      ...   ...
1368367  11597751377  2020-03-26 13:45:45  6282176142965  SC32336   SRC
1368368  11597751380  2020-03-26 13:45:47  6281216410768  SC23979   SRC
1368369  11597751391  2020-03-26 13:45:46   628124447785  SC23786   SRC
1368370  11597751397  2020-03-26 13:45:51  6281233438912  SC48639   SRC
1368371  11597751418  2020-03-26 13:46:02  6281240905188  SC51909   SRC

         sales_id product_id  amount         msisdn sd_price rs_price  status
0        RESELLER         S5    5000  6282377984589     5200     5450  Closed
1        RESELLER         S5    5000  6281397290533     5200     5450  Closed
2        RESELLER         S5    5000  6282288193047     5200     5450  Closed
3        RESELLER       SR25   25000  6285357835021    24750    25250  Closed
4        RESELLER       SR50   50000  6281337367968    49500    50000  Closed
...           ...        ...     ...            ...      ...      ...     ...
1368367  RESELLER      SR100  100000  6282180791177    96500    97000  Closed
1368368  RESELLER       IS50   50000  6285785602458    48650    49100  Closed
1368369  RESELLER        S10   10000  6281340087778    10450    10550  Closed
1368370  RESELLER       SR50   50000  6281287291384    49500    50000  Closed
1368371  RESELLER       PG20   20000    32126510919    20011    20750  Closed

[1368372 rows x 12 columns]

In [ ]:
q1_transactions.head()

,trx_id,trx_time,rs_user,rs_id,sd_id,sales_id,product_id,amount,msisdn,sd_price,rs_price,status
0,11580811934,2020-01-01 00:00:12,6281241291242,SC46886,SRC,RESELLER,S5,5000,6282377984589,5200,5450,Closed
1,11580811942,2020-01-01 00:00:24,6282274535840,SC22072,SRC,RESELLER,S5,5000,6281397290533,5200,5450,Closed
2,11580811952,2020-01-01 00:00:39,6282386610815,SC27711,SRC,RESELLER,S5,5000,6282288193047,5200,5450,Closed
3,11580811951,2020-01-01 00:00:40,6282278506522,SC13764,SRC,RESELLER,SR25,25000,6285357835021,24750,25250,Closed
4,11580811962,2020-01-01 00:00:46,6281238003443,SC35233,SRC,RESELLER,SR50,50000,6281337367968,49500,50000,Closed

In [ ]:
tabel_produk = pd.read_excel('04. table_product.xlsx')

In [ ]:
tabel_produk.head()

  product_id     description          operator  amount
0         A5  TELKOMSEL 5000  TELKOMSEL (PPOB)    5000
1        AD5  TELKOMSEL 5000  TELKOMSEL (PPOB)    5000
2       ASA5  TELKOMSEL 5000  TELKOMSEL (PPOB)    5000
3       ASB5  TELKOMSEL 5000  TELKOMSEL (PPOB)    5000
4       ASC5  TELKOMSEL 5000  TELKOMSEL (PPOB)    5000

In [ ]:
# Menggabungkan kedua tabel berdasarkan product_id
transaksi_Q1 = pd.merge(q1_transactions, tabel_produk, on='product_id', how='left')

In [ ]:
transaksi_Q1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1368370 entries, 0 to 1368371
Data columns (total 15 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   trx_id       1368370 non-null  object
 1   trx_time     1368370 non-null  datetime64[ns]
 2   rs_user      1368370 non-null  object
 3   rs_id        1368370 non-null  object
 4   sd_id        1368370 non-null  object
 5   sales_id     1368370 non-null  object
 6   product_id   1368370 non-null  object
 7   amount_x     1368370 non-null  object
 8   msisdn       1368370 non-null  object
 9   sd_price     1368370 non-null  object
 10  rs_price     1368370 non-null  object
 11  status       1368370 non-null  object
 12  description  1368370 non-null  object
 13  operator     1368370 non-null  object
 14  amount_y     1368370 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(13)
memory usage: 167.0+ MB

In [ ]:
# Konversi kolom ke tipe data yang sesuai
transaksi_Q1['amount_x'] = pd.to_numeric(transaksi_Q1['amount_x'], errors='coerce')
transaksi_Q1['sd_price'] = pd.to_numeric(transaksi_Q1['sd_price'], errors='coerce')
transaksi_Q1['rs_price'] = pd.to_numeric(transaksi_Q1['rs_price'], errors='coerce')

# Periksa apakah ada nilai NaN setelah konversi dan buang jika ada
transaksi_Q1.dropna(subset=['amount_x', 'sd_price', 'rs_price'], inplace=True)

# Verifikasi perubahan tipe data
print(transaksi_Q1.dtypes)

trx_id                 object
trx_time       datetime64[ns]
rs_user                object
rs_id                  object
sd_id                  object
sales_id               object
product_id             object
amount_x                int64
msisdn                 object
sd_price                int64
rs_price                int64
status                 object
description            object
operator               object
amount_y              float64
dtype: object

In [ ]:
# Menghapus baris dengan nilai kosong
transaksi_Q1 = transaksi_Q1.dropna()

In [ ]:
transaksi_Q1.head()

,trx_id,trx_time,rs_user,rs_id,sd_id,sales_id,product_id,amount_x,msisdn,sd_price,rs_price,status,description,operator,amount_y
0,11580811934,2020-01-01 00:00:12,6281241291242,SC46886,SRC,RESELLER,S5,5000,6282377984589,5200,5450,Closed,TELKOMSEL 5000,TELKOMSEL (PPOB),5000.0
1,11580811942,2020-01-01 00:00:24,6282274535840,SC22072,SRC,RESELLER,S5,5000,6281397290533,5200,5450,Closed,TELKOMSEL 5000,TELKOMSEL (PPOB),5000.0
2,11580811952,2020-01-01 00:00:39,6282386610815,SC27711,SRC,RESELLER,S5,5000,6282288193047,5200,5450,Closed,TELKOMSEL 5000,TELKOMSEL (PPOB),5000.0
3,11580811951,2020-01-01 00:00:40,6282278506522,SC13764,SRC,RESELLER,SR25,25000,6285357835021,24750,25250,Closed,TELKOMSEL 25000,TELKOMSEL,25000.0
4,11580811962,2020-01-01 00:00:46,6281238003443,SC35233,SRC,RESELLER,SR50,50000,6281337367968,49500,50000,Closed,TELKOMSEL 50000,TELKOMSEL,50000.0

In [ ]:
import pandas as pd

# Menghitung total transaksi
total_transaksi = transaksi_Q1['trx_id'].count()

# Menampilkan hasil
print("Total transaksi selama periode Q1 2020:", total_transaksi)

Total transaksi selama periode Q1 2020: 1368370

In [ ]:
# Menghitung total unik store
total_unik_store = transaksi_Q1['sd_id'].nunique()

# Menampilkan hasil
print("Total unik store selama periode Q1 2020:", total_unik_store)

Total unik store selama periode Q1 2020: 1

In [ ]:
total_revenue = data['rs_price'].sum()
print(f"Total revenue selama Q1 2020: {total_revenue}")

Total revenue selama Q1 2020: 35533379595.0

In [ ]:
import pandas as pd

# Konversi kolom ke tipe numerik jika perlu
transaksi_Q1['rs_price'] = pd.to_numeric(transaksi_Q1['rs_price'], errors='coerce')
transaksi_Q1['sd_price'] = pd.to_numeric(transaksi_Q1['sd_price'], errors='coerce')

# Hapus baris dengan NaN jika ada setelah konversi
transaksi_Q1.dropna(subset=['rs_price', 'sd_price'], inplace=True)

# Hitung profit margin untuk setiap transaksi
transaksi_Q1['profit_margin'] = transaksi_Q1['rs_price'] - transaksi_Q1['sd_price']

# Hitung total profit margin selama Q1 2020
total_profit_margin = transaksi_Q1['profit_margin'].sum()
print(f"Total profit margin selama Q1 2020: {total_profit_margin}")

Total profit margin selama Q1 2020: 657042261

In [ ]:
import pandas as pd

# Konversi kolom ke tipe data yang sesuai jika belum dilakukan
transaksi_Q1['sd_price'] = pd.to_numeric(transaksi_Q1['sd_price'], errors='coerce')
transaksi_Q1['rs_price'] = pd.to_numeric(transaksi_Q1['rs_price'], errors='coerce')

# Hapus baris dengan NaN jika ada setelah konversi
transaksi_Q1.dropna(subset=['sd_price', 'rs_price'], inplace=True)

# Hitung profit margin untuk setiap transaksi
transaksi_Q1['profit_margin'] = transaksi_Q1['rs_price'] - transaksi_Q1['sd_price']

# Tentukan kriteria untuk kategori produk yang berbeda
kriteria_produk = [
    "Tagihan BPJS Bukan Penerima Upah",
    "Tagihan BPJS Penerima Upah",
    "Bayar BPJS Ketenagakerjaan BPU 2 Bulan",
    "Bayar BPJS Ketenagakerjaan BPU 3 Bulan"
]

# Buat kolom untuk nett profit
def hitung_nett_profit(row):
    if row['description'] in kriteria_produk:
        return 0.30 * row['profit_margin']  # 30% untuk produk tertentu
    else:
        return 0.50 * row['profit_margin']  # 50% untuk produk lainnya

transaksi_Q1['nett_profit'] = transaksi_Q1.apply(hitung_nett_profit, axis=1)

# Hitung total nett profit
total_nett_profit = transaksi_Q1['nett_profit'].sum()
print(f"Total nett profit selama Q1 2020: {total_nett_profit}")

Total nett profit selama Q1 2020: 328521130.5

In [ ]:
import pandas as pd
import sqlite3

# Buat koneksi ke database (atau gunakan yang sudah ada)
conn = sqlite3.connect('database_transaksi.db')  # Ganti dengan nama database kamu

# SQL query untuk mendapatkan 10 produk dengan penjualan tertinggi
query = """
SELECT
    description AS product_name,
    SUM(rs_price) AS total_revenue
FROM
    transaksi_Q1
GROUP BY
    description
ORDER BY
    total_revenue DESC
LIMIT 10;
"""

# Eksekusi query dan simpan hasil ke DataFrame
top_products = pd.read_sql_query(query, conn)

# Tutup koneksi
conn.close()

# Tampilkan hasil
print(top_products)

       product_name  total_revenue
0   PLN TOKEN 50000     4424460177
1  TELKOMSEL 100000     4186312500
2  PLN TOKEN 100000     3216282518
3   TELKOMSEL 50000     3209478249
4   TELKOMSEL 10000     2739817971
5   PLN TOKEN 20000     2722660175
6   TELKOMSEL 25000     2189690895
7   Tagihan Listrik     1826920585
8  PLN TOKEN 200000     1105147600
9   TELKOMSEL 15000      924289585

In [ ]:
import pandas as pd

# Hitung total revenue per produk
top_products = transaksi_Q1.groupby('description')['rs_price'].sum().reset_index()

# Ubah nama kolom
top_products.columns = ['product_name', 'total_revenue']

# Urutkan berdasarkan total revenue secara menurun dan ambil 10 teratas
top_products = top_products.sort_values(by='total_revenue', ascending=False).head(10)

# Tampilkan hasil
print(top_products)

         product_name  total_revenue
196   PLN TOKEN 50000     4424460177
227  TELKOMSEL 100000     4186312500
193  PLN TOKEN 100000     3216282518
233   TELKOMSEL 50000     3209478249
226   TELKOMSEL 10000     2739817971
194   PLN TOKEN 20000     2722660175
230   TELKOMSEL 25000     2189690895
264   Tagihan Listrik     1826920585
195  PLN TOKEN 200000     1105147600
228   TELKOMSEL 15000      924289585

In [ ]:
import sqlite3

# Buat koneksi ke database (atau ganti dengan yang sesuai)
conn = sqlite3.connect('database_transaksi.db')  # Ganti dengan nama database kamu

# Eksekusi query untuk mendapatkan daftar tabel
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(query, conn)

# Tutup koneksi
conn.close()

# Tampilkan hasil
print(tables)

           name
0  transaksi_Q1

In [ ]:
import pandas as pd
import sqlite3

# Buat koneksi ke database
conn = sqlite3.connect('database_transaksi.db')  # Ganti dengan nama database kamu

# Hapus tabel jika sudah ada
conn.execute("DROP TABLE IF EXISTS transaksi_Q1;")

# Memasukkan DataFrame ke dalam tabel baru bernama 'transaksi_Q1'
transaksi_Q1.to_sql('transaksi_Q1', conn, if_exists='replace', index=False)

# Tutup koneksi
conn.close()

print("Data berhasil dimasukkan ke dalam database SQLite.")

Data berhasil dimasukkan ke dalam database SQLite.

In [ ]:
import sqlite3
import pandas as pd

# Hubungkan ke database
conn = sqlite3.connect('database_transaksi.db')

# Membaca tabel ke DataFrame
df = pd.read_sql_query("SELECT * FROM transaksi_Q1", conn)

# Ekspor ke CSV
df.to_csv('transaksi_Q1.csv', index=False)

# Tutup koneksi
conn.close()

In [ ]:
haha = pd.read_csv('transaksi_Q1.csv')

In [ ]:
haha.tail()

,trx_id,trx_time,rs_user,rs_id,sd_id,sales_id,product_id,amount_x,msisdn,sd_price,rs_price,status,description,operator,amount_y,profit_margin,nett_profit
1368365,11597751377,2020-03-26 13:45:45,6282176142965,SC32336,SRC,RESELLER,SR100,100000,6282180791177,96500,97000,Closed,TELKOMSEL 100000,TELKOMSEL,100000.0,500,250.0
1368366,11597751380,2020-03-26 13:45:47,6281216410768,SC23979,SRC,RESELLER,IS50,50000,6285785602458,48650,49100,Closed,INDOSAT 50000,INDOSAT,50000.0,450,225.0
1368367,11597751391,2020-03-26 13:45:46,628124447785,SC23786,SRC,RESELLER,S10,10000,6281340087778,10450,10550,Closed,TELKOMSEL 10000,TELKOMSEL (PPOB),10000.0,100,50.0
1368368,11597751397,2020-03-26 13:45:51,6281233438912,SC48639,SRC,RESELLER,SR50,50000,6281287291384,49500,50000,Closed,TELKOMSEL 50000,TELKOMSEL,50000.0,500,250.0
1368369,11597751418,2020-03-26 13:46:02,6281240905188,SC51909,SRC,RESELLER,PG20,20000,32126510919,20011,20750,Closed,PLN TOKEN 20000,PLN,20000.0,739,369.5

In [ ]:
haha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1368370 entries, 0 to 1368369
Data columns (total 17 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   trx_id         1368370 non-null  int64
 1   trx_time       1368370 non-null  object
 2   rs_user        1368370 non-null  int64
 3   rs_id          1368370 non-null  object
 4   sd_id          1368370 non-null  object
 5   sales_id       1368370 non-null  object
 6   product_id     1368370 non-null  object
 7   amount_x       1368370 non-null  int64
 8   msisdn         1368370 non-null  int64
 9   sd_price       1368370 non-null  int64
 10  rs_price       1368370 non-null  int64
 11  status         1368370 non-null  object
 12  description    1368370 non-null  object
 13  operator       1368370 non-null  object
 14  amount_y       1368370 non-null  float64
 15  profit_margin  1368370 non-null  int64
 16  nett_profit    1368370 non-null  float64
dtypes: float64(2), int64(7), object(8)
memory usage: 177.5+ MB

In [ ]:
import pandas as pd

# Daftar kolom yang ingin dihapus berdasarkan nama
columns_to_drop = ['trx_id', 'trx_time', 'rs_user', 'rs_id', 'msisdn','sales_id' , 'amount_x','description','status', 'amount_y', 'profit_margin']

# Menghapus kolom yang tidak diinginkan
transaksi_Q1_clean = haha.drop(columns=columns_to_drop)

# Menampilkan DataFrame yang sudah dibersihkan
print(transaksi_Q1_clean)

        sd_id product_id  sd_price  rs_price          operator  nett_profit
0         SRC         S5      5200      5450  TELKOMSEL (PPOB)        125.0
1         SRC         S5      5200      5450  TELKOMSEL (PPOB)        125.0
2         SRC         S5      5200      5450  TELKOMSEL (PPOB)        125.0
3         SRC       SR25     24750     25250         TELKOMSEL        250.0
4         SRC       SR50     49500     50000         TELKOMSEL        250.0
...       ...        ...       ...       ...               ...          ...
1368365   SRC      SR100     96500     97000         TELKOMSEL        250.0
1368366   SRC       IS50     48650     49100           INDOSAT        225.0
1368367   SRC        S10     10450     10550  TELKOMSEL (PPOB)         50.0
1368368   SRC       SR50     49500     50000         TELKOMSEL        250.0
1368369   SRC       PG20     20011     20750               PLN        369.5

[1368370 rows x 6 columns]

In [ ]:
transaksi_Q1_clean

        sd_id product_id  sd_price  rs_price          operator  nett_profit
0         SRC         S5      5200      5450  TELKOMSEL (PPOB)        125.0
1         SRC         S5      5200      5450  TELKOMSEL (PPOB)        125.0
2         SRC         S5      5200      5450  TELKOMSEL (PPOB)        125.0
3         SRC       SR25     24750     25250         TELKOMSEL        250.0
4         SRC       SR50     49500     50000         TELKOMSEL        250.0
...       ...        ...       ...       ...               ...          ...
1368365   SRC      SR100     96500     97000         TELKOMSEL        250.0
1368366   SRC       IS50     48650     49100           INDOSAT        225.0
1368367   SRC        S10     10450     10550  TELKOMSEL (PPOB)         50.0
1368368   SRC       SR50     49500     50000         TELKOMSEL        250.0
1368369   SRC       PG20     20011     20750               PLN        369.5

[1368370 rows x 6 columns]

In [ ]:
# Mengekspor DataFrame yang sudah dibersihkan ke file CSV
transaksi_Q1_clean.to_csv('transaksi_Q1_cleaned.csv', index=False)

print("Data berhasil diekspor ke transaksi_Q1_cleaned.csv")

Data berhasil diekspor ke transaksi_Q1_cleaned.csv

In [ ]:
# Mengekspor DataFrame yang sudah dibersihkan ke file CSV
transaksi_Q1.to_csv('transaksi_Q1.csv', index=False)

print("Data berhasil diekspor ke transaksi_Q1.csv")

Data berhasil diekspor ke transaksi_Q1.csv